git:
  requireCleanWorkingDir: false
  commitMessage: "chore: release v${version}"
github:
  release: true
  releaseName: "Release ${version}"
  tokenRef: GITHUB_TOKEN
npm:
  publish: false
repository:
  type: git
  url: "git@github.com:sriramsundhar/node-sample.git"